apiVersion: v1
kind: Service
metadata:
  name: {{ include "order-simulator.name" . }}
  labels:
    {{- include "order-simulator.labels" . | nindent 4 }}
spec:
  ports:
  - name: {{ .Values.service.portName }}
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.containerPort }}
  selector:
    {{- include "order-simulator.selectorLabels" . | nindent 4 }}
