apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  annotations:    
  labels:
    {{- include "globex-mobile.labels" . | nindent 4 }}
    app.openshift.io/runtime: nodejs
  name: {{ include "globex-mobile.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "globex-mobile.selectorLabels" . | nindent 6 }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        {{- include "globex-mobile.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "globex-mobile.serviceAccountName" . }}
      containers:
        - image:  "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Chart.Name }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: NODE_ENV
              value: {{ .Values.nodeEnv }}
            - name: PORT
              value: '{{ .Values.service.containerPort }}'
            - name: GLOBEX_MOBILE_GATEWAY
              value: {{ .Values.mobileGatewayService.url }}
            {{- if .Values.sso.enabled }}
            - name: API_CLIENT_ID
              value: {{ .Values.sso.client }}
            - name: SSO_AUTHORITY
              value: {{ .Values.sso.url }}
            - name: SSO_REDIRECT_LOGOUT_URI
              value: {{ .Values.sso.logoutUri }}
            - name: SSO_LOG_LEVEL
              value: '{{ .Values.sso.logLevel }}'
            {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
