{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "globex-mobile.serviceAccountName" . }}
  labels:
    {{- include "globex-mobile.labels" . | nindent 4 }}
{{- end }}
