hook:
  pre:
    image:
      repository: quay.io/cloud-architecture-workshop/wait-for-routes-job
      pullPolicy: IfNotPresent
      tag: "d41c5da-native"
    podSecurityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    hostPattern: ""
    argocd:
      enabled: true
      syncwave: "-1"

  post:
    image:
      repository: quay.io/cloud-architecture-workshop/trigger-pipelines-job
      pullPolicy: IfNotPresent
      tag: "e3e0ca0-native"
    podSecurityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    argocd:
      enabled: true
      syncwave: "0"

git:
  repo: https://github.com/rh-cloud-architecture-workshop/globex-3scale-devportal-template.git
  ref: main

cms:
  image: ghcr.io/fwmotion/3scale-cms:1.0.3
  contextDir: ./dev_portal
  command: "upload -u"

loop:
  prefix: user
  count: 1