{{- range untilStep 0 (.Values.loop.count | int64 | int) 1 }}
{{ $loop := printf "%s%s" $.Values.loop.prefix ((add . 1) | toString) }}
---
apiVersion: capabilities.3scale.net/v1alpha1
kind: Tenant
metadata:
  name: {{ $loop }}
  labels:
    {{- include "tenant.labels" $ | nindent 4 }}
  annotations: 
    {{- include "tenant.argocd-syncwave" $ | nindent 4 }}
spec:
  email: "{{ printf "%s@email.com" $loop  }}"
  masterCredentialsRef:
    name: system-seed
  organizationName: "{{ $.Values.tenant.organizationName }}-{{ $loop }}"
  passwordCredentialsRef:
    name: "{{ $.Values.tenant.organizationName }}-{{ $loop }}-admin-secret"
  systemMasterUrl: "{{ include "system.master-url" $ }}"
  tenantSecretRef:
    name: "{{ $.Values.tenant.organizationName }}-{{ $loop }}-tenant-secret"
    namespace: "{{ $.Release.Namespace  }}"
  username: "{{ $loop }}"
---
kind: Secret
apiVersion: v1
metadata:
  name: "{{ $.Values.tenant.organizationName }}-{{ $loop }}-admin-secret"
  labels:
    {{- include "tenant.labels" $ | nindent 4 }}
  annotations: 
    {{- include "tenant.argocd-syncwave" $ | nindent 4 }}
type: Opaque    
{{- include "tenant.admin-secret" $ }}
{{- end }}