---
kind: KeycloakRealm
apiVersion: keycloak.org/v1alpha1
metadata:
  name: globex
spec:
  instanceSelector:
    matchLabels:
      app: {{ $.Values.selector.app }}
  realm:
    id: globex
    realm: globex
    enabled: true
    displayName: globex
    eventsEnabled: false
    adminEventsEnabled: false
    accessTokenLifespanForImplicitFlow: 3600
    roles:
      realm:
        - name: admin
          composite: false
          clientRole: false
          containerId: globex
        - name: confidential
          composite: false
          clientRole: false
          containerId: globex
        - name: mobile-user
          composite: false
          clientRole: false
          containerId: globex
        - name: web-user
          composite: false
          clientRole: false
          containerId: globex
        - name: user
          composite: false
          clientRole: false
          containerId: globex
    clients:
      - clientId: globex-web-gateway
        enabled: true
        clientAuthenticatorType: client-secret
        redirectUris:
          - "*"
        webOrigins:
          - "*"
          - "+"
        standardFlowEnabled: true
        implicitFlowEnabled: true
        directAccessGrantsEnabled: true
        serviceAccountsEnabled: true
        publicClient: false
        protocol: openid-connect
        attributes:
          saml.force.post.binding: 'false'
          saml.multivalued.roles: 'false'
          frontchannel.logout.session.required: 'false'
          oauth2.device.authorization.grant.enabled: 'false'
          backchannel.logout.revoke.offline.tokens: 'false'
          saml.server.signature.keyinfo.ext: 'false'
          use.refresh.tokens: 'true'
          oidc.ciba.grant.enabled: 'false'
          backchannel.logout.session.required: 'false'
          client_credentials.use_refresh_token: 'false'
          require.pushed.authorization.requests: 'false'
          saml.client.signature: 'false'
          saml.allow.ecp.flow: 'false'
          id.token.as.detached.signature: 'false'
          saml.assertion.signature: 'false'
          client.secret.creation.time: '1679473817'
          saml.encrypt: 'false'
          saml.server.signature: 'false'
          exclude.session.state.from.auth.response: 'false'
          saml.artifact.binding: 'false'
          saml_force_name_id_format: 'false'
          acr.loa.map: "{}"
          tls.client.certificate.bound.access.tokens: 'false'
          saml.authnstatement: 'false'
          display.on.consent.screen: 'false'
          token.response.type.bearer.lower-case: 'false'
          saml.onetimeuse.condition: 'false'
        fullScopeAllowed: true
        nodeReRegistrationTimeout: -1
        protocolMappers:
          - name: Client ID
            protocol: openid-connect
            protocolMapper: oidc-usersessionmodel-note-mapper
            config:
              user.session.note: clientId
              userinfo.token.claim: 'true'
              id.token.claim: 'true'
              access.token.claim: 'true'
              claim.name: clientId
              jsonType.label: String
          - name: Client Host
            protocol: openid-connect
            protocolMapper: oidc-usersessionmodel-note-mapper
            config:
              user.session.note: clientHost
              userinfo.token.claim: 'true'
              id.token.claim: 'true'
              access.token.claim: 'true'
              claim.name: clientHost
              jsonType.label: String
          - name: Client IP Address
            protocol: openid-connect
            protocolMapper: oidc-usersessionmodel-note-mapper
            config:
              user.session.note: clientAddress
              userinfo.token.claim: 'true'
              id.token.claim: 'true'
              access.token.claim: 'true'
              claim.name: clientAddress
              jsonType.label: String
        defaultClientScopes:
          - web-origins
          - roles
          - profile
          - email
        optionalClientScopes:
          - address
          - phone
          - offline_access
          - microprofile-jwt
    users:
      - username: globex
        email: globex@email.com
        enabled: true
        realmRoles:
          - default-roles-globex
        clientRoles:
          realm-management:
            - realm-admin
            - manage-realm
            - manage-clients
        credentials:
          - type: password
            value: openshift
      - username : asilva
        email: asilva@email.com
        enabled: true
        realmRoles:
          - default-roles-globex
          - web-user
        credentials:
          - type: password
            value: openshift
      - username: mmiller
        email: mmiller@topvibe.com
        enabled: true
        realmRoles:
          - default-roles-globex
          - web-user
        credentials:
          - type: password
            value: openshift
      - username: asanders
        email: asanders@topgreatest.com
        enabled: true
        realmRoles:
          - default-roles-globex
          - web-user
        credentials:
          - type: password
            value: openshift
      - username: cjones
        email: cjones@zmail.com
        enabled: true
        realmRoles:
          - default-roles-globex
          - web-user
        credentials:
          - type: password
            value: openshift
      - username: pwong
        email: pwong@email.com
        enabled: true
        realmRoles:
          - default-roles-globex
          - web-user
        credentials:
          - type: password
            value: openshift
