apiVersion: v1
kind: Secret
metadata:
  name: {{ include "globex-partner-web.name" . }}
  labels:
    {{- include "globex-partner-web.labels" . | nindent 4 }}
type: "Opaque"
data:
  api-client-id: {{ .Values.api.clientid | b64enc }}
  api-client-secret: {{ .Values.api.clientsecret | b64enc }}
  api-token-url: {{ .Values.api.tokenurl | b64enc}}

  