{{- if .Values.minio.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio.name" . }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
  annotations: 
    {{- if .Values.argocd.enabled }}
    {{- include "minio.argocd-syncwave" . | nindent 4 }}
    {{- else }}
    "helm.sh/hook": pre-install  
    {{- end }}
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    {{- include "minio.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
{{- end }}
