{{- if .Values.minio.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "minio.name" . }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
  annotations: 
    {{- if .Values.argocd.enabled }}
    {{- include "minio.argocd-syncwave" . | nindent 4 }}
    {{- else }}
    "helm.sh/hook": pre-install  
    {{- end }}
spec:
  port:
    targetPort: 9000
  to:
    kind: Service
    name: {{ include "minio.name" . }}
    weight: 100
  wildcardPolicy: None
  {{- if .Values.minio.route.tlsEnabled }}
  tls:
    {{- toYaml .Values.minio.route.tls | nindent 4 }}
  {{ end }}
{{- end }}
