pgsql:
  service: service-registry-db
  database: apicurio
  user: apicurio
  password: apicurio

route:
  enabled: true
  host: 
  tlsEnabled: true
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

ingress:
  disabled: true

resources:
  limits:
    cpu: 250m
    memory: 512Mi
  requests:
    cpu: 125m
    memory: 512Mi
