kind: Secret
apiVersion: v1
metadata:
  name: {{ include "rhsso-db.secretName" . }}
  labels:
    {{- include "rhsso-db.labels" . | nindent 4 }}
    app: {{ .Values.selector.app }}
  annotations:
    {{- include "rhsso-db.argocd-syncwave" . | nindent 4 }}
stringData:
  POSTGRES_DATABASE: {{ .Values.pgsql.database }}
  POSTGRES_EXTERNAL_ADDRESS: {{ include "rhsso-db.name" . }}.{{ .Release.Namespace }}.svc.cluster.local
  POSTGRES_EXTERNAL_PORT: '5432'
  POSTGRES_PASSWORD: {{ .Values.pgsql.password }}
  POSTGRES_USERNAME:  {{ .Values.pgsql.user }}
type: Opaque
