kafka-broker:
  authentication:
    securityProtocol: SASL_PLAINTEXT
    saslMechanism: SCRAM-SHA-512
    clientId: globex
    clientSecret: globex
kafka-topics:
  kafka:
    namespace:
kafdrop:
  kafka:
    bootstrapServer: ""
    securityProtocol: SASL_PLAINTEXT
    saslMechanism: SCRAM-SHA-512
    clientId: globex
    clientSecret: globex
    namespace: ""
