kind: Secret
apiVersion: v1
metadata:
  name: system-seed
  labels:
    {{- include "apimanager.labels" . | nindent 4 }}
  annotations:
    {{- include "apimanager.argocd-syncwave" . | nindent 4 }}
{{- include "system-seed.secret" . }}
type: Opaque
