kind: Secret
apiVersion: v1
metadata:
  name: system-smtp
  labels:
    {{- include "apimanager.labels" . | nindent 4 }}
  annotations:
    {{- include "apimanager.argocd-syncwave" . | nindent 4 }}
type: Opaque    
stringData:
  address: "{{ .Values.smtp.host }}"
  authentication: "{{ .Values.smtp.authentication }}"
  domain: "{{ .Values.smtp.domain }}"
  openssl.verify.mode: '{{ .Values.smtp.sslVerify }}'
  password: "{{ .Values.smtp.password }}"
  port: "{{ .Values.smtp.port }}"
  username: "{{ .Values.smtp.userId }}"
